"""Public Python API for SlyBrowser."""

from .errors import (
    ArtifactError,
    ConfigurationError,
    LicenseError,
    LicenseServiceError,
    LICENSE_SERVICE_ERROR_CODES,
    is_license_service_error_code,
    ManifestError,
    SlyBrowserError,
    WebDriverError,
)
from .browser import (
    launch_playwright,
    launch_playwright_async,
    launch_playwright_persistent,
    launch_playwright_persistent_async,
)
from .automation import AutomationBackend, AutomationCapability, automation_capability, validate_playwright_version
from .launcher import LaunchPlan, prepare_launch
from .webdriver import (
    HumanizeConfig,
    SlyWebDriverElement,
    SlyWebDriverService,
    SlyWebDriverSession,
    WebDriverVersions,
    launch,
    launch_webdriver,
)
from .license import LicenseClaims, LicenseVerifier
from .manifest import ReleaseManifest, verify_release_manifest
from .installer import BrowserInstallation, install_granted_browser
from .licensed import (
    install_authorized,
    install_latest,
    launch_authorized,
    launch_authorized_playwright,
    launch_authorized_playwright_async,
    launch_authorized_playwright_persistent,
    launch_authorized_playwright_persistent_async,
    launch_latest,
    launch_latest_playwright,
    launch_latest_playwright_async,
    launch_latest_playwright_persistent,
    launch_latest_playwright_persistent_async,
    prepare_authorized_browser,
    prepare_latest_authorized_browser,
)
from .service import (
    LicenseAuthorization,
    LicenseInfo,
    LicenseServiceClient,
    LicensedSessionGrant,
    RuntimeActivationGrant,
    RuntimeDownloadTicket,
    RuntimeHeartbeatGrant,
    RuntimeSessionGrant,
    SealedLicenseImportResult,
    import_license_file_to_sealed_authorization,
    read_license_authorization,
)

__all__ = [
    "ArtifactError",
    "AutomationBackend",
    "AutomationCapability",
    "ConfigurationError",
    "LaunchPlan",
    "LicenseClaims",
    "LicenseError",
    "LicenseServiceError",
    "LICENSE_SERVICE_ERROR_CODES",
    "is_license_service_error_code",
    "LicenseVerifier",
    "ManifestError",
    "ReleaseManifest",
    "SlyBrowserError",
    "WebDriverError",
    "HumanizeConfig",
    "SlyWebDriverElement",
    "SlyWebDriverService",
    "SlyWebDriverSession",
    "WebDriverVersions",
    "launch",
    "launch_webdriver",
    "launch_playwright",
    "launch_playwright_async",
    "launch_playwright_persistent",
    "launch_playwright_persistent_async",
    "automation_capability",
    "validate_playwright_version",
    "prepare_launch",
    "verify_release_manifest",
    "BrowserInstallation",
    "LicenseAuthorization",
    "LicenseInfo",
    "LicenseServiceClient",
    "LicensedSessionGrant",
    "RuntimeActivationGrant",
    "RuntimeDownloadTicket",
    "RuntimeHeartbeatGrant",
    "RuntimeSessionGrant",
    "SealedLicenseImportResult",
    "install_granted_browser",
    "install_authorized",
    "install_latest",
    "launch_authorized",
    "launch_authorized_playwright",
    "launch_authorized_playwright_async",
    "launch_authorized_playwright_persistent",
    "launch_authorized_playwright_persistent_async",
    "launch_latest",
    "launch_latest_playwright",
    "launch_latest_playwright_async",
    "launch_latest_playwright_persistent",
    "launch_latest_playwright_persistent_async",
    "prepare_authorized_browser",
    "prepare_latest_authorized_browser",
    "import_license_file_to_sealed_authorization",
    "read_license_authorization",
]

__version__ = "0.1.0"
